"""Idempotent, explicitly labelled demonstration catalogue and customer activity.

These are fictional products and reviews, never training/evaluation records.
AI reports are generated by the actual inference service during first startup.
Existing accounts, passwords, privileges and moderated reviews are never reset.
"""
from datetime import datetime, timedelta, timezone
import json
import os

from backend import database as db


PRODUCTS = [
    {
        "seed_key": "aura-headphones", "name": "Aura Wireless Headphones",
        "category": "Audio", "price": 1499, "image_key": "headphones",
        "description": "A little more focus. A lot more music. Lightweight over-ear wireless headphones with soft cushions, rich sound and an all-day battery for your everyday rhythm.",
        "specifications": {"Battery": "Up to 30 hours", "Connectivity": "Bluetooth 5.3", "Weight": "220 g", "Driver": "40 mm"},
    },
    {
        "seed_key": "pulse-watch", "name": "Pulse Smart Watch",
        "category": "Wearables", "price": 2299, "image_key": "smartwatch",
        "description": "Keep your day in view. A crisp display, activity tracking and everyday notifications in a comfortable, lightweight watch. Designed for daily fitness awareness.",
        "specifications": {"Display": "1.8-inch colour", "Battery": "Up to 7 days", "Resistance": "IP67", "Strap": "Silicone"},
    },
    {
        "seed_key": "typepro-keyboard", "name": "TypePro Mechanical Keyboard",
        "category": "Accessories", "price": 3499, "image_key": "keyboard",
        "description": "Make every keystroke count. A compact mechanical keyboard with tactile switches, adjustable backlighting and a sturdy frame for study, work and play.",
        "specifications": {"Layout": "75% compact", "Switches": "Tactile", "Connection": "USB-C", "Backlight": "Adjustable RGB"},
    },
    {
        "seed_key": "echo-speaker", "name": "Echo Portable Speaker",
        "category": "Audio", "price": 1799, "image_key": "speaker",
        "description": "Bring your playlist along. A compact, splash-resistant speaker with balanced sound and a handy carry loop, made for small gatherings and slow afternoons.",
        "specifications": {"Output": "12 W", "Battery": "Up to 12 hours", "Resistance": "IPX5", "Connectivity": "Bluetooth 5.2"},
    },
    {
        "seed_key": "air-earbuds", "name": "Air Mini Earbuds",
        "category": "Audio", "price": 1299, "image_key": "earbuds",
        "description": "Small case, everyday sound. Comfortable wireless earbuds with touch controls, clear calling and a pocket-sized charging case for your commute.",
        "specifications": {"Playback": "Up to 24 hours with case", "Charging": "USB-C", "Weight": "4 g per earbud", "Controls": "Touch"},
    },
    {
        "seed_key": "swift-mouse", "name": "Swift Ergonomic Mouse",
        "category": "Accessories", "price": 899, "image_key": "mouse",
        "description": "Comfort through the workday. A sculpted wireless mouse with quiet clicks, adjustable sensitivity and a reliable connection for your desk setup.",
        "specifications": {"Sensitivity": "800–2400 DPI", "Connection": "2.4 GHz wireless", "Buttons": "6", "Battery": "1 AA"},
    },
]

# customer index, product key, rating, text, completed demonstration purchase
REVIEWS = [
    (0, "aura-headphones", 4, "I have used these headphones for two weeks on my commute. The sound quality is clear and the ear cushions are comfortable. Battery life is average, but they are good value for the price.", True),
    (1, "aura-headphones", 3, "The sound is good for podcasts and the headphones fit comfortably. However, the Bluetooth connection drops when I move to another room and the battery is disappointing.", True),
    (2, "aura-headphones", 5, "Absolutely amazing amazing amazing! Best headphones ever, perfect sound, perfect battery, perfect everything. Everyone must buy this product right now, five stars guaranteed!", False),
    (0, "pulse-watch", 4, "The watch display is bright and easy to read outdoors. Step tracking seems reasonable on my daily walk. The strap is comfortable, although the app connection sometimes takes a second attempt.", True),
    (1, "pulse-watch", 2, "After a week the watch battery barely lasts two days. The display looks nice, but notifications often arrive late. I am disappointed with the connectivity and would not buy it again.", True),
    (2, "pulse-watch", 5, "Excellent watch, excellent quality, excellent price! This is the greatest product I have ever purchased. Absolutely flawless and highly recommended to every single person!", False),
    (1, "typepro-keyboard", 5, "I write code every day and the keyboard feels solid. The keys are responsive and the build quality is excellent. The compact layout saved desk space, though the switches are a little loud.", True),
    (2, "typepro-keyboard", 4, "The keyboard arrived in good condition. Typing feels comfortable and the backlight is useful at night. The cable is a bit short for my desk, but overall it is worth the price.", True),
    (0, "echo-speaker", 4, "This speaker is good for a small room. Vocals sound clear and pairing with my phone was easy. Bass gets weak at high volume, but the battery lasted through our afternoon picnic.", True),
    (1, "echo-speaker", 3, "The speaker is easy to carry and the build quality seems decent. Sound is average at this price. I wish the battery lasted longer; I get around six hours rather than a full day.", False),
    (1, "air-earbuds", 2, "The earbuds sound fine indoors, but calls outside are poor. My friends hear too much traffic noise and the left earbud sometimes loses connection. The case is compact but I cannot recommend them for calls.", True),
    (2, "air-earbuds", 4, "These earbuds fit my ears comfortably and stay in place on the train. Sound quality is good for the price. Touch controls are sensitive, so I sometimes pause music by accident.", False),
    (1, "swift-mouse", 5, "The mouse is comfortable during long study sessions. The quiet clicks and smooth tracking are great. I have used it for three weeks without a connection problem and it is good value.", True),
    (2, "swift-mouse", 3, "This mouse works as expected on my laptop. The shape is comfortable, but the scroll wheel feels loose. The wireless connection is stable. Reasonable for the price, with average build quality.", False),
]


def seed_catalogue():
    """Initialize fictional products without creating shared login accounts."""
    db.create_tables()
    with db._cursor() as cursor:
        for product in PRODUCTS:
            exists = db._execute(cursor, "SELECT id FROM products WHERE seed_key = ?", (product["seed_key"],)).fetchone()
            if not exists:
                db._execute(cursor, """INSERT INTO products
                    (seed_key, name, description, category, price, image_key, specifications, is_demo)
                    VALUES (?, ?, ?, ?, ?, ?, ?, 1)""",
                    (product["seed_key"], product["name"], product["description"], product["category"],
                     product["price"], product["image_key"], json.dumps(product["specifications"])))


def seed_demo(analyze_fn, hash_password):
    if os.getenv("SEED_DEMO", "true").strip().lower() not in ("1", "true", "yes", "on"):
        return {"seeded": False, "reason": "Demo seeding disabled"}
    seed_catalogue()
    account_specs = [
        ("Alex Morgan", "customer@reviewguard.demo", "Demo@12345", "customer"),
        ("Priya Sharma", "priya@reviewguard.demo", "Demo@12345", "customer"),
        ("Sam Wilson", "sam@reviewguard.demo", "Demo@12345", "customer"),
        ("ReviewGuard Admin", "admin@reviewguard.demo", "Admin@12345", "admin"),
    ]
    customers = []
    for name, email, password, role in account_specs:
        user = db.get_user_by_email(email)
        if user is None:
            user = db.create_user(name, email, hash_password(password), role, is_demo=True)
        # Never promote, reset or seed activity into a pre-existing real account.
        customers.append(user if user.get("is_demo") and user["role"] == role else None)
    products = {product["seed_key"]: product for product in db.list_products()}
    inserted = 0
    for index, (customer_index, key, rating, review, purchased) in enumerate(REVIEWS):
        user, product = customers[customer_index], products[key]
        if user is None:
            continue
        existing = db.get_user_reviews(user["id"])
        if any(item["product_id"] == product["id"] for item in existing):
            continue
        created_at = datetime.now(timezone.utc) - timedelta(days=18 - index)
        if purchased and not db.has_purchase(user["id"], product["id"]):
            order = db.create_order(user["id"], product["id"])
            with db._cursor() as cursor:
                db._execute(cursor, "UPDATE customer_orders SET created_at = ? WHERE id = ?",
                            (db._timestamp(created_at - timedelta(days=7)), order["id"]))
        context = {
            **db.user_review_context(user["id"], review),
            "verified_purchase": db.has_purchase(user["id"], product["id"]),
            "product_id": product["id"], "product_name": product["name"],
            "category": product["category"], "rating": rating,
            "product": {"name": product["name"], "category": product["category"]},
        }
        analysis = analyze_fn(review, context=context)
        db.create_product_review(user["id"], product["id"], rating, review, analysis,
                                 is_demo=True, created_at=created_at)
        inserted += 1
    return {"seeded": True, "products": len(PRODUCTS), "reviews_created": inserted}
